version: 2.1

jobs:
  build-and-test:
    docker:
      - image: cimg/base:current

    steps:
      - checkout
      - run:
          name: "Build Docker image"
          command: docker build -t django-app .

workflows:
  django-integration:
    jobs:
      - build-and-test
